# some basic word types
identifier    $= alpha alphanum*
number        $= numeral+

# control structures
emptyline     := endl
dim           := "dim"~ identifier "="~ number endl~

# the program
prog          := (dim | emptyline) EOF